apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: proxy-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 3
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /health_check
    port: 80