apiVersion: v1
kind: Service
metadata:
  name: cstack-auth-backend-service
  labels:
    app: cstack-auth-backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: cstack-auth-backend