apiVersion: apps/v1
kind: Deployment
metadata:
  name: cstack-auth-backend-deployment
  labels:
    app: cstack-auth-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: cstack-auth-backend
  template:
    metadata:
      labels:
        app: cstack-auth-backend
    spec:
      containers:
        - name: cstack-auth-backend-container
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.backend.env.secret }}
          ports:
            -  containerPort: 8000