apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: celery-beat-volume
  name: celery-beat-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.celerybeat.storage }}