apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: celery-volume
  name: celery-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.celery.storage }}