apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  labels:
    app: proxy
spec:
  replicas: {{ .Values.proxy.replicaCount }}
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: UPSTREAM_HOST
              value: {{ .Values.proxy.upstreamhost }}
            - name: UPSTREAM_PORT
              value: "{{ .Values.proxy.upstreamport }}"